service: chaos-mod-gh-bot
useDotenv: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  profile: "${env:AWS_PROFILE}"
  role: "arn:aws:iam::${env:AWS_ID}:role/${env:AWS_ROLE}-${self:provider.stage}"
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: ${self:custom.logs.retention.${self:provider.stage}, 7}
  environment:
    ENV: ${self:provider.stage}
    REGION: ${self:provider.region}
    SERVICE_NAME: ${self:service}-${self:provider.stage}

custom:
  logs:
    retention:
      production: 14
      dev: 7
  webpack:
    webpackConfig: ./webpack.config.js
    packager: 'npm'
    includeModules:
      forceExclude:
        - dotenv 
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5
  domain:
    enabled:
      production: true
      dev: false
      local: false

functions:
  healthcheck:
    handler: src/v1/healthcheck/get.handler
    description: Basic page ok healthcheck
    events:
      - http:
          path: v1/healthcheck
          method: get
  hookHandler:
    handler: src/v1/hook/post.handler
    description: Handler of github webhooks
    events:
      - http:
          path: v1/hook
          method: post
    
plugins:
  - serverless-webpack
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-offline
